training_pipeline_config:
  pipeline_name: networksecurity
  artifact_dir: artifact

data_ingestion_config:
   database_name: Tamilselvan0
   collection_name: Network_Data
   raw_data_dir: raw_data
   raw_data_file_name: phisingData.csv
   ingested_data_dir: ingested_data
   ingested_train_data_dir: train
   ingested_test_data_dir: test
   ingested_train_data_file_name: train.csv
   ingested_test_data_file_name: test.csv
   train_test_split_ratio: 0.20

data_validation_config:
   schema_dir: config
   schema_file_name: schema.yaml
   valid_data_dir: valid
   invalid_data_dir: invalid
   drift_report_dir: drift_report
   report_file_name: report.yaml   

data_transformation_config:
   transformed_dir: transformed_data
   transformed_train_dir: train
   transformed_test_dir: test
   preprocessor_dir: preprocessor
   preprocessor_object_file_name: preprocessor.pkl

model_trainer_config:
   trained_model_dir: trained_model
   model_file_name: model.pkl
   base_accuracy: 0.6
   diff_test_train_acc: 0.05
   model_config_dir: config
   model_config_file_name: model.yaml

model_evaluation_config:
   model_evaluation_file_name: model_evaluation.yaml

model_pusher_config:
   model_export_dir: saved_models